### ISSUE TITLE
Bug: missing settings labels

### ISSUE THREAD

**Issue by Krislunde** [boazpoolman/strapi-plugin-sitemap#151] opened 2023-12-13 11:21 UTC
### Describe the bug

Some settings labels are missing/have broken label paths. Specifically the `Priority` and `Changefreq` entries as seen in attached screenshot.

<img width="849" alt="Screenshot 2023-12-13 at 22 17 13" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/5624240/bff5a63f-a1ce-4e77-9445-8d04da6d911d">

**Comment by MSACC** [comment] 2023-12-16 20:27
Can you be more clear please? The Priority and Changefreq are not updating in the sitemap?

**Comment by MSACC** [comment] 2023-12-16 21:55
I cannot reproduce this bug. Priority and Changefreq are changing as soon as I change it. Did you click the 'Save' button in the right upper corner to make sure you saved your changes in your URL bundle?

<img width="1036" alt="image" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/35879908/cbac8213-9c01-48a4-8eb2-68173e772f34">
<img width="602" alt="image" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/35879908/8db642f6-301f-44a1-831b-2d99e7070541">

**Comment by Krislunde** [comment] 2023-12-18 05:36
No, I mean the actual label /description for the field in the admin interface. You can see it in my screenshot. Look UNDER the fields in the image: instead of whatever label you intended, it says `sitemap.Settings.Priority.Description` and `sitemap.Settings.Field.Changefreq.Description`. The other labels/descriptions look fine.

**Comment by TMSchipper** [comment] 2023-12-19 21:11
Hi @Krislunde this should be fixed with this pull [request](https://github.com/boazpoolman/strapi-plugin-sitemap/pull/152) 
We will first test this and will create asap an new release with the fix. 

Thanks for the feedback!

**Comment by boazpoolman** [comment] 2023-12-22 07:33
This was released with version `3.0.7` of the plugin

**Closed by boazpoolman** 2023-12-22 07:33 UTC
Labels: bug
